password: ENC[AES256_GCM,data:oqAQpVEao2b3VWQpywUuI3K7tcFff5mf,iv:b+HRV6CaTHuavy15Cuwl6VTc6RnoNaa88U1A90nWcNg=,tag:4VlORtRsOWDuJNBGgwEEOw==,type:str]
api_encryption_key: ENC[AES256_GCM,data:KAJREHMcBx754Hqs+uUv3OdpB0qMQLVVS3bOqtkyUuWAPiVKVIeqy8l5N+U=,iv:nQnDR9qocdZVOPI26W3b/RiVYB9QFKjrJoTl1HAA+CI=,tag:hNsiLZbz7c0kwpGiCLYQrg==,type:str]
wifi_ssid: ENC[AES256_GCM,data:UIRXslmo,iv:wUQVJu/6kbvqKWpHfwZlGfggyDusaQpslFKVH3dXePY=,tag:u/bB3CqFBNbjWYIGeXCnbQ==,type:str]
wifi_password: ENC[AES256_GCM,data:li/cebt97VdqRutyjw==,iv:eLBPW7g2+L1NLvqocfcwxqNuV/UsXURsx4dl962SLMM=,tag:ImIlaxWPMEG2PY7+CUXWzg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/tuxnet-385112/locations/europe/keyRings/infrastructure-encryption/cryptoKeys/infrastructure-encryption
          created_at: "2023-06-05T15:14:45Z"
          enc: CiQA9PdEcFKcePOUQMV/McBDcrpqzz48XRdiU0OXlEWZ0Mda0jISSQA2N6cC3pxgMOZA07FyAIB8J7+WnFpyjiKmpkd+HEv6AYlLCbfazQD9fmiLmp7VVg3OsONd0940NNSeA+bT9iFLyDAVuFgH2U4=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-06-05T15:14:45Z"
    mac: ENC[AES256_GCM,data:hwabUo8g3/WAY8gFIGIFehqVMpz+ULPuAIGnXFWhnHI3QrwbvFZA2CpSuz4Jxj5v6HckQJkTnR0A9JfZmimslN7ENAaB2avIA0a3xV+k2QYrnOsumo3ZZuE0JoUr1qWgk5BAe/QIlzZaZySAOlb53yAcBDcqhopZjlUzrwurEq8=,iv:9ROM/JrZqetJ9R3rdOzmHsJzDdlNSFsTxS3mWxxYdSc=,tag:BgtY9HnL9Q0r9TaXGIBL8w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
