---
name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Firmware
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - uses: mdgreenwald/mozilla-sops-action@55177c1ff20a2b396280e4c5f53c32b69f0c1e40 # v2.1.1

      - uses: hashicorp/vault-action@892a26828f195e65540a40b4768ae4571f51ebfc # v4.0.0
        id: import-secrets
        with:
          method: jwt
          url: ${{ secrets.VAULT_ADDR }}
          path: ${{ secrets.VAULT_PATH }}
          role: ${{ secrets.VAULT_ROLE }}
          secrets: |
            github-homelab-esphome-firmware/data/scaleway organization_id | SCW_ORGANIZATION_ID ;
            github-homelab-esphome-firmware/data/scaleway project_id | SCW_PROJECT_ID ;
            github-homelab-esphome-firmware/data/scaleway region | SCW_DEFAULT_REGION ;
            github-homelab-esphome-firmware/data/scaleway zone | SCW_DEFAULT_ZONE ;
            github-homelab-esphome-firmware/data/scaleway access_key | SCW_ACCESS_KEY ;
            github-homelab-esphome-firmware/data/scaleway secret_key | SCW_SECRET_KEY

      - run: |
          pip install s3cmd --no-cache

      - run: |
          ./scripts/secrets_crypter.sh d

      - uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          tags: builder:latest
          push: false
      - uses: addnab/docker-run-action@4f65fabd2431ebc8d299f8e5a018d79a769ae185 # v3
        with:
          image: builder:latest
          options: -v ${{ github.workspace }}:/workspace
          run: |
            cd /workspace
            ./scripts/build_firmware.sh

      - run: |
          ./scripts/upload_firmware.sh infrastructure-assets-5274ba70-fde0-47de-8e9a-f1bc64c11157/esphome/firmware
