---
name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  conform:
    runs-on: ubuntu-latest
    name: Conform

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: siderolabs/conform@v0.1.0-alpha.27
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  yamllint:
    runs-on: ubuntu-latest
    name: YAML Lint

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: |
          yamllint .

  verify:
    runs-on: ubuntu-latest
    name: Verify Builds
    strategy:
      matrix:
        esphome-version: ["2023.5.5"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: mdgreenwald/mozilla-sops-action@v1.4.1

      - run: |
          ./scripts/secrets_crypter.sh d
        env:
          CLOUDSDK_COMPUTE_REGION: "${{ secrets.CLOUDSDK_COMPUTE_REGION }}"
          CLOUDSDK_CORE_PROJECT: "${{ secrets.CLOUDSDK_CORE_PROJECT }}"
          GOOGLE_CREDENTIALS: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}"

      - uses: addnab/docker-run-action@v3
        with:
          image: esphome/esphome:${{ matrix.esphome-version }}
          options: -v ${{ github.workspace }}:/workspace
          run: |
            cd /workspace
            ./scripts/build_firmware.sh
