---
name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  conform:
    runs-on: ubuntu-latest
    name: Conform

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: siderolabs/conform@v0.1.0-alpha.27
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  yamllint:
    runs-on: ubuntu-latest
    name: YAML Lint

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          yamllint .

  verify:
    runs-on: ubuntu-latest
    name: Verify Builds

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: mdgreenwald/mozilla-sops-action@v1.6.0

      - uses: hashicorp/vault-action@v3
        id: import-secrets
        with:
          method: jwt
          url: ${{ secrets.VAULT_ADDR }}
          path: ${{ secrets.VAULT_PATH }}
          role: ${{ secrets.VAULT_ROLE }}
          secrets: |
            github-homelab-esphome-firmware/data/google-cloud region | CLOUDSDK_COMPUTE_REGION ;
            github-homelab-esphome-firmware/data/google-cloud workload_identity_provider | GOOGLE_WORKLOAD_IDENTITY_PROVIDER ;
            github-homelab-esphome-firmware/data/google-cloud ci_service_account | GOOGLE_WORKLOAD_IDENTITY_SERVICE_ACCOUNT

      - uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ env.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GOOGLE_WORKLOAD_IDENTITY_SERVICE_ACCOUNT }}

      - run: |
          ./scripts/secrets_crypter.sh d

      - uses: docker/build-push-action@v6
        with:
          tags: builder:latest
          push: false
      - uses: addnab/docker-run-action@v3
        with:
          image: builder:latest
          options: -v ${{ github.workspace }}:/workspace
          run: |
            cd /workspace
            ./scripts/build_firmware.sh
