---
name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  conform:
    runs-on: ubuntu-latest
    name: Conform

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: siderolabs/conform@v0.1.0-alpha.27
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  yamllint:
    runs-on: ubuntu-latest
    name: YAML Lint

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          yamllint .

  verify:
    runs-on: ubuntu-latest
    name: Verify Builds

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: mdgreenwald/mozilla-sops-action@v1.6.0

      - uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_SERVICE_ACCOUNT }}

      - run: |
          ./scripts/secrets_crypter.sh d
        env:
          CLOUDSDK_COMPUTE_REGION: "${{ secrets.CLOUDSDK_COMPUTE_REGION }}"

      - uses: docker/build-push-action@v5
        with:
          tags: builder:latest
          push: false
      - uses: addnab/docker-run-action@v3
        with:
          image: builder:latest
          options: -v ${{ github.workspace }}:/workspace
          run: |
            cd /workspace
            ./scripts/build_firmware.sh
